Update upd7220.c
src\emu\video\upd7220.c(1590) : error C2220: warning treated as error - no 'object' file generated
src\emu\video\upd7220.c(1590) : warning C4804: '>>' : unsafe use of type 'bool' in operation
make: *** [obj/vwindowsd/emu/video/upd7220.o] Error 2

Just added a cast, something better obviously needs to be done?