Fixed compile error. C:/MAME/src/devices/machine/hp_taco.h:50:14: error: 'virtual int hp_taco_device::call_display(std::__cxx11::string&)' marked 'override', but does not override   virtual int call_display(std::string& s) override;               ^ In file included from ../../../../../src/emu/emu.h:70:0: C:/MAME/src/emu/diimage.h:155:22: error: 'virtual std::__cxx11::string device_image_interface::call_display()' was hidden [-Werror=overloaded-virtual]   virtual std::string call_display() { return std::string(); }                       ^ In file included from ../../../../../src/mame/drivers/hp9845.cpp:35:0: C:/MAME/src/devices/machine/hp_taco.h:50:14: error:   by 'virtual int hp_taco_device::call_display(std::__cxx11::string&)' [-Werror=overloaded-virtual]   virtual int call_display(std::string& s) override;               ^
If "override" removed, this happened:

Compiling src/mame/drivers/hp9845.cpp...
In file included from ../../../../../src/emu/emu.h:70:0:
C:/MAME/src/emu/diimage.h:155:22: error: 'virtual std::__cxx11::string device_image_interface::call_display()' was hidden [-Werror=overloaded-virtual]
  virtual std::string call_display() { return std::string(); }
                      ^
In file included from ../../../../../src/mame/drivers/hp9845.cpp:35:0:
C:/MAME/src/devices/machine/hp_taco.h:50:14: error:   by 'virtual int hp_taco_device::call_display(std::__cxx11::string&)' [-Werror=overloaded-virtual]
  virtual int call_display(std::string& s);
              ^
Compiling src/devices/machine/hp_taco.cpp...
In file included from ../../../../../src/emu/emu.h:70:0:
C:/MAME/src/emu/diimage.h:155:22: error: 'virtual std::__cxx11::string device_image_interface::call_display()' was hidden [-Werror=overloaded-virtual]
  virtual std::string call_display() { return std::string(); }
                      ^
In file included from ../../../../../src/devices/machine/hp_taco.cpp:141:0:
C:/MAME/src/devices/machine/hp_taco.h:50:14: error:   by 'virtual int hp_taco_device::call_display(std::__cxx11::string&)' [-Werror=overloaded-virtual]
  virtual int call_display(std::string& s);
              ^

So, the call was renamed in order for compilation to proceed.