Get rid of the assert replacement.  It prevents you from using assert in a destructor for a literal type due to the implicit nothrow.  It's just not worth the trouble it's causing.
In file included from ../../../../../src/emu/emu.h:83:
../../../../../src/emu/mconfig.h:70:5: error: '~token' has a non-throwing exception specification but can still throw [-Werror,-Wexceptions]
                               assert(m_device == m_host.m_current_device);
                               ^
In file included from ../../../../../src/emu/emu.h:29:
../../../../../src/emu/emucore.h:230:48: note: expanded from macro 'assert'
 #define assert(x)               do { if (!(x)) throw emu_fatalerror("assert: %s:%d: %s", __FILE__, __LINE__, #x); } while (0)
                                              ^
In file included from ../../../../../src/emu/emu.h:83:
../../../../../src/emu/mconfig.h:66:3: note: destructor has a implicit non-throwing exception specification
               ~token()
               ^
1 error generated.